# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5848cfc943c5c6423ce2559e4e1e94e258ad81bebb6cccf299423cd032e0b97f512ac525d324049a2c62823469ee499b6904e5cd1acd94a2adcb98fa3e07f2

test:
  secret_key_base: d1d27f2ae58b30d92f510da5e149350fb344cab3c054ab4e6e254d225c6eea0e37ab89bbf124563638405d0dec8317ea9ea0ec9597bb82cec292a052237a7287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
